#pragma once

#include "signal_processing/convolution.hpp"
#include "signal_processing/correlation.hpp"
#include "signal_processing/dct.hpp"
#include "signal_processing/dst.hpp"
#include "signal_processing/fft.hpp"
#include "signal_processing/fir.hpp"
#include "signal_processing/fir_design.hpp"
#include "signal_processing/hartley.hpp"
#include "signal_processing/iir.hpp"
#include "signal_processing/iir_design.hpp"
#include "signal_processing/mdct.hpp"
#include "signal_processing/resampling.hpp"
#include "signal_processing/walsh_hadamard.hpp"
#include "signal_processing/windows.hpp"
